import {
  getCategories,
  ensureColumnsExist,
  getAllMenuItems,
  getArchivedMenuItems,
  getMenuItemById,
  getCustomizationsByMenuItemId,
  getMasterCustomizations,
} from './menu/menuQuery';
import {
  createMenuItem,
  updateMenuItem,
  updateInventoryStatus,
  toggleHideMenuItem,
  deleteMenuItem,
  restoreMenuItem,
  permanentDeleteMenuItem,
  addCustomizationOption,
  updateCustomizationOption,
  deleteCustomizationOption,
  addMasterCustomization,
  updateMasterCustomization,
  deleteMasterCustomization,
} from './menu/menuMutation';

export const menuService = {
  getCategories,
  ensureColumnsExist,
  getAllMenuItems,
  getArchivedMenuItems,
  getMenuItemById,
  createMenuItem,
  updateMenuItem,
  updateInventoryStatus,
  toggleHideMenuItem,
  deleteMenuItem,
  restoreMenuItem,
  permanentDeleteMenuItem,
  getCustomizationsByMenuItemId,
  addCustomizationOption,
  updateCustomizationOption,
  deleteCustomizationOption,
  getMasterCustomizations,
  addMasterCustomization,
  updateMasterCustomization,
  deleteMasterCustomization,
};
